#!/usr/bin/env bash                                                                                                                                       
# Fix nginx to listen on port 80

# Go to sites-enabled folder for Nginx                                                                                                                    
cd /etc/nginx/sites-enabled/ || exit;                                                                                                                             
# Delete the default file                                                                                                                               
rm default;                                                                                                                                               
# Create a symbolic link to the default file in sites-available                                                                                             
ln -s /etc/nginx/sites-available/default default;                                                                                                         
# Restart Nginx                                                                                                                                           
service nginx restart 
