#!/usr/bin/env bash
# transfer a file from the client to a remote server using scp with ssh key authentication.

# check if the correct number of arguments is provided
if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# assign parameters to named variables for readability
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# use scp to transfer the file to the remote server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "${username}@${server_ip}:~/"

# check the exit status of scp command
if [ $? -eq 0 ]; then
  echo "File transfer successful"
else
  echo "File transfer failed"
fi
