#!/usr/bin/env bash
# Configure Nginx to redirect /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4 with a 301 status

apt-get update
apt-get install -y nginx
echo 'Holberton School for the win!' > /var/www/html/index.html
sed -i '/server_name _;/a \ \n    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }\n' /etc/nginx/sites-available/default
service nginx reload || nginx -s reload
