#!/usr/bin/env bash
# Configure Nginx so that the custom 404 page returns "Ceci n'est pas une page"

apt-get update -y && apt-get install nginx -y
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/^\s*error_page/d' /etc/nginx/sites-available/default
sed -i '/server_name _;/a \    error_page 404 \/custom_404.html;\n    location = \/custom_404.html {\n        internal;\n    }' /etc/nginx/sites-available/default
service nginx reload || nginx -s reload
